Basic_User/urls.py
from django.conf.urls import url
from django.urls import path
from Basic_User import views


app_name='Basic_User'


urlpatterns=[
    path('register/', views.register,name='register'),
    path('user_login/', views.user_login,name='user_login'),
]

djangoLoginUsers/urls.py
from django.contrib import admin
from django.urls import path,include
from Basic_User import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name='index'),
    path('Basic_User/', include('Basic_User.urls')),
    path('logout/', views.user_logout,name='logout'),
    path('special/', views.special,name='special'),
]

Basic_User/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileModel(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site=models.URLField(blank=True)
    profile_image=models.ImageField(upload_to='profile_pics', blank=True)


    def __str__(self):
        return self.user.username

Basic_User/forms.py
from django import forms
from Basic_User.models import UserProfileModel
from django.contrib.auth.models import User

class UserProfileForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model=User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model=UserProfileModel
        fields=('portfolio_site','profile_image')

Basic_User/views.py
from django.shortcuts import render
from Basic_User.forms import UserProfileForm, UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate,login,logout

# Create your views here.
def index(request):
    return render(request,'Basic_User/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False

    if request.method=='POST':
        user_form = UserProfileForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user

            if 'profile_image' in request.FILES:
                profile.profile_image=request.FILES['profile_image']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form= UserProfileForm()
        profile_form=UserProfileInfoForm()

    return render(request,'Basic_User/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})


def user_login(request):
    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACount is not active")
        else:
            print("Soemone tried to login and failed")
            print("Username:  {} and password {)".format(username,password))
            return HttpResponse("Invalifd credentials")
    else:
        return render(request,'Basic_User/login.html')

templates/Basic_User/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <ul class="navbar-nav">
          <li class="nav-item active"><a href="{% url 'index' %}" class="navbar-brand">Home</a></li>
          <li class="nav-item"><a href="{% url 'admin:index' %}" class="nav-link">Admin</a></li>
          <li class="nav-item"><a href="{% url 'Basic_User:register' %}" class="nav-link">Registration</a></li>
          {% if user.is_authenticated %}
            <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Logout</a></li>
          {% else %}
             <li class="nav-item"><a href="{% url 'Basic_User:user_login' %}" class="nav-link">Login</a></li>
          {% endif %}
      </ul>
    </div>
</nav>
   <div class="container">
       {% block body_block %}
       {% endblock %}
   </div>
</body>
</html>

templates/Basic_User/index.html
<!DOCTYPE html>
{% extends "Basic_User/base.html" %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Index File</h1>
    </div>
{% endblock %}

templates/Basic_User/login.html
<!DOCTYPE html>
{% extends "Basic_User/base.html" %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Please Login</h1>
    <form action="{% url "Basic_User:user_login" %}" method="POST">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">
    <label for="password">Password:</label>
    <input type="password" name="password" placeholder="Enter Password">

        <input type="submit" name="" value="Login">
    </form>
    </div>
{% endblock %}

templates/Basic_User/registration.html
<!DOCTYPE html>
{% extends "Basic_User/base.html" %}
{% load static %}
{% block body_block %}
    <div class="jumbotron">
    {% if registered %}
        <h1>Thanks for Registring</h1>
        {% else %}
        <h1>Register Here</h1>
        <h3>Fill Out the form</h3>
        <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{  profile_form.as_p}}
        <input type="submit" value="register">
        </form>
    {% endif %}
    </div>
{% endblock %}